//
// Copyright (c) 2010-2025 Antmicro
//
// This file is licensed under the MIT License.
// Full license text is available in 'licenses/MIT.txt'.
//
#ifndef PcieEndpoint_H
#define PcieEndpoint_H
#include "bus.h"
#include <atomic>
#include <condition_variable>
#include <mutex>
#include <thread>

// PCIe endpoint bus class — transaction layer for a Verilated PCIe endpoint.
//
// The RTL clock is free-running in a dedicated thread (startClock()). BAR
// transactions from the host arrive as signal events in that running stream,
// not as stop-start stimuli. DMA and interrupts are generated by the clock
// thread at any point between transactions.
//
// TLP mapping:
//   MWr  (host→device, posted write)  → write()  posts PendingTxn, clock thread drives signals
//   MRd  (host→device, non-posted)    → read()   posts PendingTxn, returns bar_rdata when bar_rdy
//   DMA write (device→host)           → clock thread detects dma_wen, calls pushDoubleWordToAgent
//   DMA read  (device←host)           → clock thread detects dma_ren, calls requestDoubleWordFromAgent
//   MSI-X                             → clock thread calls agent->handleInterrupts() every cycle;
//                                        register with agent->registerInterrupt(irq, 0) in sim_main.cpp
//
// Usage in sim_main.cpp:
//   RenodeAgent* Init() {
//       auto* agent = new RenodeAgent();
//       auto* bus   = new PcieEndpoint();
//       bus->clk = &top->clk;  // wire all signal pointers
//       // ...
//       agent->addBus(bus);    // calls setAgent() — wires evaluateModel
//       agent->registerInterrupt(bus->irq, 0);
//       bus->startClock();     // start free-running clock AFTER setAgent()
//       return agent;
//   }
struct PcieEndpoint : public BaseTargetBus
{
    // ── Public interface ──────────────────────────────────────────────────

    // Start / stop the free-running clock thread.
    // startClock() must be called after agent->addBus(this) (which calls setAgent
    // and wires evaluateModel).  stopClock() is called automatically by reset().
    void startClock();
    void stopClock();

    // BaseTargetBus — called by RenodeAgent::writeToBus / readFromBus.
    // These post a PendingTxn and block until the clock thread completes it.
    // They do NOT call tick() directly.
    virtual void     write(int width, uint64_t addr, uint64_t value);
    virtual uint64_t read(int width, uint64_t addr);

    virtual void tick(bool countEnable, uint64_t steps);
    virtual void timeoutTick(uint8_t* signal, uint8_t expectedValue, int timeout);
    virtual void reset();
    virtual bool areSignalsConnected();

    // ── BAR slave interface (host → device) ──────────────────────────────
    uint8_t  *clk      = nullptr;
    uint8_t  *rst      = nullptr;
    uint64_t *bar_addr = nullptr;   // byte offset within BAR
    uint32_t *bar_wdata = nullptr;  // write data  (32-bit — PCIe MWr payload)
    uint32_t *bar_rdata = nullptr;  // read data   (32-bit — CplD payload)
    uint8_t  *bar_wen  = nullptr;   // asserted for the setup cycle on MWr
    uint8_t  *bar_ren  = nullptr;   // asserted on MRd; held until bar_rdy
    uint8_t  *bar_rdy  = nullptr;   // RTL asserts when the cycle is complete

    // ── DMA initiator interface (device → host) ───────────────────────────
    // RTL drives dma_wen or dma_ren for one cycle with valid dma_addr /
    // dma_wdata.  The clock thread drives dma_rdy for one cycle on completion.
    uint64_t *dma_addr  = nullptr;
    uint32_t *dma_wdata = nullptr;
    uint32_t *dma_rdata = nullptr;
    uint8_t  *dma_wen   = nullptr;
    uint8_t  *dma_ren   = nullptr;
    uint8_t  *dma_rdy   = nullptr;

    // ── MSI-X ─────────────────────────────────────────────────────────────
    // Wire this to the RTL's interrupt output and call
    // agent->registerInterrupt(bus->irq, 0) before startClock().
    uint8_t  *irq = nullptr;

private:
    // ── Transaction queue (main thread → clock thread) ────────────────────
    struct PendingTxn {
        int      width;
        uint64_t addr;
        uint64_t wdata;
        bool     is_read;
        bool     valid;
    };

    struct TxnResponse {
        uint64_t rdata;
        bool     valid;
    };

    void clockLoop();
    void handleDma();   // called from clockLoop() — clock thread owns sender_fd

    std::thread             clock_thread;
    std::atomic<bool>       clock_running{false};

    std::mutex              txn_mutex;
    PendingTxn              pending_txn{};

    std::mutex              resp_mutex;
    std::condition_variable resp_cv;
    TxnResponse             txn_response{};
};
#endif
